# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

PROJECT_NAME = "RNCICDDemo"
XCODE_PROJECT = "./ios/#{PROJECT_NAME}.xcodeproj"
XCODE_WORKSPACE = "./ios/#{PROJECT_NAME}.xcworkspace"
OUTPUT_DIRECTORY = "./fastlane/builds"
IPA_DIRECTORY = "#{OUTPUT_DIRECTORY}/#{PROJECT_NAME}.ipa"
BUILD_FOR_DEVELOPMENT_ONLY = false # true = Build for Development | false = Build to create a release
BUILD_ONLY = true

default_platform(:ios)

platform :ios do

  private_lane :build do
    configuration_name = "Release"
    export_options_method = "development"
    code_sign_identity = "iPhone Developer"
    PROJECT_APP_ID = ENV["APP_IDENTIFIER"]
    PROJECT_PROFILE = "match Development #{ENV["APP_IDENTIFIER"]}"
    PROJECT_TEAM = ENV["DEVELOPER_TEAM_ID"]
    
    increment_build_number(xcodeproj: XCODE_PROJECT)
    
    increment_version_number_in_xcodeproj(
      bump_type: "patch",
      xcodeproj: XCODE_PROJECT,
    )

    settings_to_override = {
      :BUNDLE_IDENTIFIER => PROJECT_APP_ID,
      :PROVISIONING_PROFILE_SPECIFIER => PROJECT_PROFILE,
      :DEVELOPMENT_TEAM => PROJECT_TEAM,
    }

    create_keychain(
      name: ENV["CI_KEYCHAIN_NAME"],
      password: ENV["CI_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    match(
      app_identifier: ENV["APP_IDENTIFIER"],
      git_url: ENV["GIT_REPO_URL"],
      type: "development",
      username: ENV["APPLE_ID"],
      team_id: ENV["DEVELOPER_TEAM_ID"],
      keychain_name: ENV["CI_KEYCHAIN_NAME"],
      keychain_password: ENV["CI_KEYCHAIN_PASSWORD"],
      readonly: true
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: XCODE_PROJECT,
      code_sign_identity: code_sign_identity,
      bundle_identifier: PROJECT_APP_ID,
      profile_name: PROJECT_PROFILE
    )

    gym(
      scheme: PROJECT_NAME,
      workspace: XCODE_WORKSPACE,
      silent: true,
      configuration: configuration_name,
      xcargs: `#{settings_to_override} -UseNewBuildSystem=YES`,
      output_directory: OUTPUT_DIRECTORY,
      output_name: "#{PROJECT_NAME}.ipa",
      export_options: {
        method: "development",
        signingStyle: "manual",
        provisioningProfiles: { 
            PROJECT_APP_ID => PROJECT_PROFILE
        }
      }
    )

    upload_to_testflight(
      username: ENV["APPLE_ID"],
      app_identifier: ENV["APP_IDENTIFIER"],
      team_id: ENV["APPSTORE_TEAM_ID"],
      ipa: IPA_DIRECTORY
    )

  end
  desc "Create Signed IPA Build"
  lane :beta do
    build
  end
end