# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # increment_version_code('app_project_dir': '/home/runner/work/RNCICDDemo/RNCICDDemo/android/app')

    # gradle(
    #   task: "bundle",
    #   build_type: "Release",
    #   print_command: false,
    #   properties: {
    #     "android.injected.signing.store.file" => ENV["KEYSTORE_FILE"],
    #     "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
    #     "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
    #     "android.injected.signing.key.password" => ENV["KEY_PASSWORD"]
    #   }
    # )

    upload_to_play_store(
      json_key: ENV["ANDROID_JSON_KEY_FILE"],
      track: "internal",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
      aab: ENV["ANDROID_SIGNED_AAB"]
    )
  end
end
