name: CI/CD Android Next
on:
  push:
    branches:
      - next

jobs:
  deploy:
    name: Deploying to Play Store
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install

      #   - name: Setup JDK
      #     uses: actions/setup-java@v1
      #     with:
      #       java-version: 16

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
          working-directory: "android"

      - name: Install Fastlane
        run: |
          bundle install
          bundle update fastlane

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "serviceAccount.json"
          encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

      #   - name: Generate private-decoded-key.json file
      #     run: echo ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }} | base64 -d > /home/runner/work/${{ secrets.PROJECT_NAME }}/${{ secrets.PROJECT_NAME }}/service_account_key.json

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: release_keystore
        with:
          fileName: "release.jks"
          encodedString: ${{ secrets.ANDROID_KEYSTORE_FILE }}

      #   - name: Generate .keystore file
      #     run: echo ${{ secrets.ANDROID_KEYSTORE_FILE }} | base64 -d > /home/runner/work/${{ secrets.PROJECT_NAME }}/${{ secrets.PROJECT_NAME }}/app/release.keystore

      - name: Define version code with offset
        env:
          RUN_NUMBER: ${{ github.run_number }}
          INITIAL_VERSION_CODE: 73
        run: |
          VERSION_CODE=$((INITIAL_VERSION_CODE + RUN_NUMBER))
          echo "version_code=$VERSION_CODE" >> $GITHUB_ENV

      - name: Update version code
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: android/app/build.gradle
          versionCode: ${{ env.version_code }}

      - name: Build & deploy Android release
        run: cd android && bundle exec fastlane android deploy
        env:
          ANDROID_KEYSTORE_FILE: ${{ steps.release_keystore.outputs.filePath }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS}}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_JSON_KEY_FILE: ${{ steps.service_account_json_file.outputs.filePath }}

      - run: echo "${{ secrets.PROJECT_NAME }}-Android build has been successfully deployed to Play store console 🎉"
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Notify deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.1
        id: rollbar_deploy
        with:
            environment: "test"
            version: ${{ github.sha }}
        env:
            ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
            ROLLBAR_USERNAME: ${{ github.actor }}
