name: Slack Notification Workflow

on:
  workflow_call:
    inputs:
      DISPLAY_NAME:
        type: string
      VERSION:
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      GITHUB:
        required: true

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - uses: actions/checkout@v2
        with:
          repository: smashtaps/devops
          ref: main
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v1.23.0
        id: slack
        with:
          payload-file-path: "templates/slack/success_template.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
