name: Slack Notification Workflow

on:
  workflow_call:
    inputs:
      DISPLAY_NAME:
        type: string
      VERSION:
        type: string
    secrets:
      SMASHTAPS_SLACK_WEBHOOK_URL:
        required: true

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.23.0
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: actions/checkout@v2
        with:
          payload-file-path: "./templates/slack/success.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SMASHTAPS_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
