name: Slack Notification Workflow

on:
  workflow_call:
    inputs:
      DISPLAY_NAME:
        type: string
      VERSION:
        type: string
      JOB_STATUS:
        type: string
      GITHUB_USER:
        type: string
      GITHUB_REPOSITORY:
        type: string
      GITHUB_BRANCH:
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  read_package_json:
    name: Read Package JSON
    runs-on: ubuntu-latest
    outputs:
      displayName: ${{ steps.read_package.outputs.displayName }}
      version: ${{ steps.read_package.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Read package json
        uses: Muchaszewski/read-json-action@1.0.0
        id: read_package
        with:
          path: "package.json"
          properties: "displayName, version"
  
  send_slack_notification:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    needs: read_package_json
    steps:
      - name: Setup Ndde environment
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
        
      - name: Check out devops repo
        uses: actions/checkout@v2
        with:
          repository: smashtaps/devops
          ref: main
          
      - name: Read Slack notification success template
        id: slack_success_template_file
        uses: juliangruber/read-file-action@v1
        with:
          path: ./templates/slack/success_template.json
          
      - name: Prepare Slack Template
        id: slack_template
        env:
          JOB_STATUS: ${{ inputs.JOB_STATUS }}
          GITHUB_USER: ${{ inputs.GITHUB_USER }}
          DISPLAY_NAME: ${{ needs.read_package.outputs.displayName }}
          VERSION: ${{ needs.read_package.outputs.version }}
          GITHUB_REPOSITORY: ${{ inputs.GITHUB_REPOSITORY }}
          GITHUB_BRANCH: ${{ inputs.GITHUB_BRANCH }}
        uses: AndreasNel/string-vars-action@master
        with:
          instring: ${{ steps.slack_success_template_file.outputs.content }}
          
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.23.0
        id: slack
        with:
          payload: ${{ steps.slack_template.outputs.outstring }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
